Kotlin and dependencies versions updated
googlecodelabs/exoplayer-intro pull request #75
Opened 2021-12-15 23:38 UTC by osuleymanova

Kotlin and Gradle Plugin versions updated
android:exported="true" added in Manifest
jcenter() replaced by mavenCentral()
exoplayer version updated
appcompat dependency updated

2021-12-16 15:42 UTC, JoseAlcerreca approved these changes

2021-12-16 15:47 UTC, JoseAlcerreca commented
I'll let Don merge

2021-12-16 16:11 UTC, dturner requested changes

2021-12-16 16:11 UTC, dturner commented on exoplayer-codelab-01/build.gradle
> +    implementation 'com.google.android.exoplayer:exoplayer-core:2.16.1'
Unfortunately it's not possible to upgrade from ExoPlayer 2.12 to 2.16 without making some code changes. Please could we revert these version updates.

2021-12-16 16:51 UTC, JoseAlcerreca approved these changes

2022-01-04 13:15 UTC, dturner approved these changes

2022-01-04 13:15 UTC, merged